settings:
  title: 'Train In Blocks Status Page'
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: traininblocks-com
    name: Train In Blocks Landing Site
    description: 'Our main site with blog'
    url: 'https://traininblocks.com'

  - id: api-traininblocks-com
    name: Train In Blocks API
    description: 'Needed for the app to save your data'
    url: 'https://api.traininblocks.com'
    expectStatus: 401

  - id: app-traininblocks-com
    name: Train In Blocks App
    description: 'Our kickass app'
    url: 'https://app.traininblocks.com'
    
  - id: auth-traininblocks-com
    name: Train In Blocks Auth
    description: 'Needed for you to login to the app'
    url: 'https://auth.traininblocks.com'
