settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: traininblocks-com # unique identifier
    name: Train In Blocks Landing Site
    url: 'https://traininblocks.com'

  - id: api-traininblocks-com
    name: Train In Blocks API
    url: 'https://api.traininblocks.com'
    method: GET
    expectStatus: 401

  - id: app-traininblocks-com
    name: Train In Blocks App
    url: 'https://app.traininblocks.com'
    
  - id: auth-traininblocks-com
    name: Train In Blocks Auth
    url: 'https://auth.traininblocks.com'
